ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/rgbw/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/magnetometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/barometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/humidity/inc
obj-y := sensor_dts.o
