ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/magnetometer/inc
obj-y += mag.o mag_factory.o
obj-$(CONFIG_MTK_AKM09911_NEW) += akm09911-new/
obj-$(CONFIG_MTK_ST480) += st480/
