ccflags-y += -I$(srctree)/drivers/misc/mediatek/m681-sensors/hwmon/include
obj-y += alsps.o alsps_factory.o aal_control.o
obj-$(CONFIG_MTK_LTR579) += ltr579/
obj-$(CONFIG_MTK_PA12200001) += pa12200001/
