GUD_ROOT_FOLDER := $(srctree)/drivers/misc/mediatek/gud/302c/gud/
# Release mode by default
ccflags-y := -DNDEBUG
ccflags-y += -Wno-declaration-after-statement

ccflags-$(CONFIG_MOBICORE_DEBUG) += -DDEBUG
ccflags-$(CONFIG_MOBICORE_VERBOSE) += -DDEBUG_VERBOSE

# Choose one platform from the folder
#MOBICORE_PLATFORM := $(shell (ls -1 $(GUD_ROOT_FOLDER)MobiCoreDriver/platforms | tail -1) )
ccflags-y += -DMC_NETLINK_COMPAT_V37

# Use the available platform folder
#ccflags-y += -I$(GUD_ROOT_FOLDER)MobiCoreDriver/platforms/$(MOBICORE_PLATFORM)
# MobiCore Driver includes
ccflags-y += -I$(GUD_ROOT_FOLDER)MobiCoreDriver/public
# MobiCore KernelApi required includes
ccflags-y += -I$(GUD_ROOT_FOLDER)MobiCoreKernelApi/include \
		-I$(GUD_ROOT_FOLDER)MobiCoreKernelApi/public

# MobiCore TlcTui required includes
ccflags-y += -I$(GUD_ROOT_FOLDER)/TlcTui \
		     -I$(GUD_ROOT_FOLDER)/TlcTui/inc \
		     -I$(GUD_ROOT_FOLDER)/TlcTui/public

ccflags-y += -I$(GUD_ROOT_FOLDER)
